# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import trades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(default=trades.models.generate_id, max_length=9, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('sell_currency', models.CharField(max_length=3, verbose_name='Sell currency')),
                ('sell_amount', models.FloatField(verbose_name='Sell amount')),
                ('buy_currency', models.CharField(max_length=3, verbose_name='Buy currency')),
                ('buy_amount', models.FloatField(verbose_name='Buy amount')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('date_booked', models.DateTimeField(auto_now=True, verbose_name='Date booked')),
            ],
        ),
    ]
